version: "3.5"

services:
  get-stock-data:
    build:
      context: ./get-stock-data
      dockerfile: Dockerfile
    command: ["python", "./run_app.py", 'GOOG', 'AABA', 'FB', 'MSFT', 'TWTR', 'AAPL', 'JPM', 'AMZN', 'JNJ', 'BAC'] # stock symbols
    secrets:
      - alphavantag_api_key
      - mongo_initdb_root_password
    environment:
      ALPHAVANTAG_API_KEY_FILE: /run/secrets/alphavantag_api_key
      MONGO_INITDB_ROOT_USERNAME: ece568
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
      MONGO_HOST: mongodb
      PYTHONUNBUFFERED: "1"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    secrets:
      - mongo_initdb_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: ece568
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongdb-config:/data/configdb

  mongodb-express:
    image: mongo-express
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ./mongo-express-config.js
        target: /node_modules/mongo-express/config.js
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb


secrets:
  alphavantag_api_key:
    file: ./alphavantag_api_key
  mongo_initdb_root_password:
    file: ./mongo_initdb_root_password

volumes:
  mongodb-data:
  mongdb-config: