version: "3.6"

services:
  prediction:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    secrets:
      - mongodb_password
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          cpus: '0.7'
    environment:
      PYTHONUNBUFFERED: "1"
      MONGODB_USERNAME: ece568
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGODB_HOST: zwithc.cn

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8080:8080"
    volumes:
      - ./web/target/FinalProject.war:/usr/local/tomcat/webapps/ROOT.war
      - ./web/target/FinalProject:/usr/local/tomcat/webapps/ROOT

secrets:
  mongodb_password:
    file: ./mongo_initdb_root_password