version: "3.5"

services:
  get-stock-data:
    build: .
    command: ["python", "./run_app.py", "GOOG", "FB"] # stock symbols
    secrets:
      - alphavantag_api_key
      - postgres_password
    environment:
      ALPHAVANTAG_API_KEY_FILE: /run/secrets/alphavantag_api_key
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres

  postgres:
    image: postgres
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

secrets:
  alphavantag_api_key:
    file: ./alphavantag_api_key.txt
  postgres_password:
    file: ./postgres_password.txt

volumes:
  postgres-data: